spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.26.198.103:3306/committee?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除 1代表删除 0代表已删除
      logic-delete-value: 1
      logic-not-delete-value: 0
call-parameters:
  systemcode: KAOHE
  version: 1.0
  key: KAOHE_123456
call-URL:
  baseUrl: 59.202.74.92:9000/jc-report/
  getUserByOrgIdUrl: api/getUserList
  getEventReportCountUrl: api/getEventReportCount
  getEventDealCountUrl: /api/getEventDealCount
  getUserDealCountUrl: /api/getUserDealCount
  getUserYawpCountUrl: /api/getUserYawpCount